basePath: /
host: localhost:1323
info:
  contact:
    email: dung@productsway.com
    name: Dung Huynh
    url: http://productsway.com
  description: Blog API collections
  title: Golang Blog API
  version: "1.0"
paths: {}
swagger: "2.0"
