-- CreateTable
CREATE TABLE "Comment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "content" TEXT NOT NULL,
    "postID" TEXT NOT NULL,
    FOREIGN KEY ("postID") REFERENCES "Post" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
